---
- name: Install AD Domain Services
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Create forest if not present
  ansible.windows.win_domain:
    dns_domain_name: "{{ contoso_fqdn }}"
    safe_mode_password: "{{ dsrm_password }}"
    domain_mode: WinThreshold    # adjust if guide requires specific level
    forest_mode: WinThreshold
    install_dns: yes
  register: forest_create

- name: Reboot if forest creation required
  ansible.windows.win_reboot:
    msg: "Rebooting after forest creation"
    pre_reboot_delay: 10
  when: forest_create.reboot_required | default(false)