all:
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

    # Credentials from Vault
    ansible_user: "{{ vault_local_admin_user }}"
    ansible_password: "{{ vault_local_admin_password }}"

  children:
    windows:
      hosts:
        ContosoDC1:
          ansible_host: 192.168.2.51
        ContosoDC2:
          ansible_host: 192.168.2.52
        ChildDC1:
          ansible_host: 192.168.2.53
        ChildDC2:
          ansible_host: 192.168.2.55
        ChildDC3:
          ansible_host: 192.168.2.56
        FabrikamDC1:
          ansible_host: 192.168.2.54
        Client1:
          ansible_host: 192.168.2.65
        Client2:
          ansible_host: 192.168.2.66
        Server1:
          ansible_host: 192.168.2.67