all:
  vars:
    # WinRM over HTTPS (preferred)
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_scheme: https
    ansible_winrm_transport: basic     # or 'ntlm' if you have SPNs/creds set
    ansible_winrm_server_cert_validation: ignore

    # Pre-join: use local admin (from image build/terraform var)
    ansible_user: "{{ local_admin_user }}"
    ansible_password: "{{ local_admin_password }}"

    # Post-join: tasks that require domain admin will use:
    domain_admin_user: "{{ vault_domain_admin_user }}"
    domain_admin_password: "{{ vault_domain_admin_password }}"
    dsrm_password: "{{ vault_dsrm_password }}"

  children:
    contoso_dcs:
      hosts:
        ContosoDC1:
          ansible_host: "<IP_ContosoDC1>"
        ContosoDC2:
          ansible_host: "<IP_ContosoDC2>"

    child_dcs:   # If child domain(s) exist
      hosts:
        ChildDC1:
          ansible_host: "<IP_ChildDC1>"
        ChildDC2:
          ansible_host: "<IP_ChildDC2>"
        ChildDC3:
          ansible_host: "<IP_ChildDC3>"

    fabrikam_dcs:  # If Fabrikam is a separate forest (or a child/sibling per guide)
      hosts:
        FabrikamDC1:
          ansible_host: "<IP_FabrikamDC1>"

    members:
      hosts:
        Client1:
          ansible_host: "<IP_Client1>"
        Client2:
          ansible_host: "<IP_Client2>"
        Server1:
          ansible_host: "<IP_Server1>"

    # Helpful supergroups for targeting
    all_dcs:
      children:
        contoso_dcs
        child_dcs
        fabrikam_dcs