# ---------- Domain topology ----------
contoso_fqdn: "contoso.com"
contoso_netbios: "CONTOSO"

child_fqdns:
  - "child.contoso.com"

fabrikam_fqdn: "fabrikam.com"
fabrikam_netbios: "FABRIKAM"

# ---------- Sites & Services ----------
ad_sites:
  - name: "Default-First-Site-Name"

# ---------- DNS config ----------
contoso_dns_servers:
  - "10.0.1.4"   # ContosoDC1
  - "10.0.1.5"   # ContosoDC2

child_dns_servers:
  - "10.0.2.4"   # ChildDC1

fabrikam_dns_servers:
  - "10.0.3.4"   # FabrikamDC1

dns_forwarders:
  - "168.63.129.16"

# ---------- Connection settings for Ansible ----------
ansible_connection: winrm
ansible_port: 5985                      # Use 5985 for HTTP bootstrap; switch to 5986 after HTTPS
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

# Pull credentials from Vault
ansible_user: "{{ vault_local_admin_user }}"
ansible_password: "{{ vault_local_admin_password }}"

# ---------- Credentials for AD tasks ----------
local_admin_user: "{{ vault_local_admin_user }}"
local_admin_password: "{{ vault_local_admin_password }}"
domain_admin_user: "{{ vault_domain_admin_user }}"
domain_admin_password: "{{ vault_domain_admin_password }}"
dsrm_password: "{{ vault_dsrm_password }}"

# ---------- Role mappings ----------
forest_root_dc: "ContosoDC1"
additional_contoso_dcs:
  - "ContosoDC2"

child_domain_dcs:
  "child.contoso.com":
    - "ChildDC1"
    - "ChildDC2"
    - "ChildDC3"

fabrikam_forest_dcs:
  - "FabrikamDC1"

contoso_members:
  - "Client1"
  - "Client2"
  - "Server1"

# ---------- OU / GPO / Objects ----------
ou_structure:
  - name: "Corp"
    path: "DC=CONTOSO,DC=COM"
  - name: "Servers"
    path: "OU=Corp,DC=CONTOSO,DC=COM"

ad_users:
  - name: "LabUser1"
    upn: "LabUser1@contoso.com"
    password: "{{ vault_labuser1_password }}"
    path: "OU=Corp,DC=CONTOSO,DC=COM"
    groups: ["Helpdesk"]

ad_groups:
  - name: "Helpdesk"
    scope: "global"
    path: "OU=Corp,DC=CONTOSO,DC=COM"

# ---------- Trusts ----------
trusts:
  - source_forest: "contoso.com"
    target_forest: "fabrikam.com"
    direction: "two-way"
    selective_auth: false
    transitive: true