---
- name: Promote ContosoDC2 as additional DC in contoso.com
  hosts: ContosoDC2
  gather_facts: no
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  roles:
    - ad-additional-dc