---
# Forwarders are idempotent via community.windows.win_dns_server_forwarder
- name: Ensure DNS forwarders are configured
  community.windows.win_dns_server_forwarder:
    forwarders: "{{ dns_forwarders }}"
    clear_existing: false
    state: present

# Example: conditional forwarder between forests (Contoso <-> Fabrikam) if required
- name: Conditional forwarder to Fabrikam (if trust planned)
  community.windows.win_dns_server_setting:
    zone_type: "ConditionalForwarder"
    name: "{{ fabrikam_fqdn }}"
    master_servers: "{{ fabrikam_dns_servers | default([]) }}"
    replication_scope: "Forest"
  when:
    - fabrikam_fqdn is defined
    - fabrikam_dns_servers | length > 0