---
- name: Ensure DNS Server role is present (if not already via AD DS)
  ansible.windows.win_feature:
    name: DNS
    include_management_tools: yes
    state: present

- name: Configure DNS forwarders (idempotent)
  community.windows.win_dns_server_forwarder:
    forwarders: "{{ dns_forwarders }}"
    clear_existing: false
    state: present

# Optional: conditional forwarder to Fabrikam (if you plan trusts)
- name: Conditional forwarder to Fabrikam (optional)
  community.windows.win_dns_server_zone:
    name: "{{ fabrikam_fqdn }}"
    type: ConditionalForwarder
    replication_scope: Forest
    master_servers: "{{ fabrikam_dns_servers | default([]) }}"
  when:
    - fabrikam_fqdn is defined
    - fabrikam_dns_servers | length > 0