---
# Promote current host to an additional DC in an existing domain
- name: Ensure AD DS binaries are present
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Promote to additional DC in {{ contoso_fqdn }} (microsoft.ad.domain_controller)
  microsoft.ad.domain_controller:
    domain_name: "{{ contoso_fqdn }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ dsrm_password }}"
    state: domain_controller
  register: add_dc

- name: Reboot after DC promotion if required
  ansible.windows.win_reboot:
    msg: "Rebooting after DC promotion"
    reboot_timeout: 1800
  when: add_dc.reboot_required | default(false)